/// <reference path="../pb_data/types.d.ts" />

// Call signaling collection — the PocketBase counterpart of the Firestore
// `calls` collection. Applied automatically on server start.
migrate(
  (app) => {
    const collection = new Collection({
      type: "base",
      name: "calls",

      fields: [
        // The id is supplied by the client, not autogenerated: it is the same
        // value used as the CallKit call UUID on iOS, so it MUST stay a valid
        // 36-char hyphenated UUID. PocketBase's default id field is 15 lowercase
        // alphanumerics, which would reject it — hence the widened bounds and a
        // pattern that permits hyphens and uppercase.
        {
          type: "text",
          name: "id",
          system: true,
          primaryKey: true,
          required: true,
          min: 15,
          max: 36,
          pattern: "^[a-zA-Z0-9-]+$",
          autogeneratePattern: "[a-z0-9]{15}",
        },

        { type: "text", name: "callerId", required: true, max: 255 },
        { type: "text", name: "calleeId", required: true, max: 255 },
        { type: "text", name: "callerName", max: 255 },
        { type: "text", name: "callerPhone", max: 64 },
        { type: "bool", name: "isVideo" },

        {
          type: "select",
          name: "state",
          required: true,
          maxSelect: 1,
          values: [
            "ringing",
            "accepted",
            "declined",
            "cancelled",
            "missed",
            "ended",
          ],
        },

        // Fallback authority for missed calls: the caller's own 45s timer
        // normally writes `missed`, but a crashed caller would leave the record
        // ringing forever. The cron sweep in pb_hooks/calls.pb.js reads this.
        { type: "date", name: "ringExpiresAt" },
        { type: "date", name: "acceptedAt" },
        { type: "date", name: "endedAt" },
        { type: "text", name: "endedBy", max: 255 },

        { type: "autodate", name: "created", onCreate: true },
        { type: "autodate", name: "updated", onCreate: true, onUpdate: true },
      ],

      // Only the two participants can ever see a call.
      listRule:
        '@request.auth.id != "" && (callerId = @request.auth.id || calleeId = @request.auth.id)',
      viewRule:
        '@request.auth.id != "" && (callerId = @request.auth.id || calleeId = @request.auth.id)',

      // You may only start a call as yourself, only in `ringing`, and not to
      // yourself.
      createRule:
        '@request.auth.id != "" && @request.body.callerId = @request.auth.id && @request.body.state = "ringing" && @request.body.calleeId != @request.body.callerId',

      // Participant-only. The legal-transition state machine and field
      // immutability are enforced in pb_hooks/calls.pb.js, which can compare
      // against the stored record without depending on which fields a partial
      // update happens to include.
      updateRule:
        '@request.auth.id != "" && (callerId = @request.auth.id || calleeId = @request.auth.id)',

      // Call history is never client-deletable.
      deleteRule: null,

      indexes: [
        "CREATE INDEX idx_calls_callee_created ON calls (calleeId, created)",
        "CREATE INDEX idx_calls_state_expires ON calls (state, ringExpiresAt)",
      ],
    })

    app.save(collection)
  },
  (app) => {
    app.delete(app.findCollectionByNameOrId("calls"))
  },
)
